### ISSUE TITLE
Question: HR Managment system

### ISSUE THREAD

**Issue by 13LuckyBack** [MusheAbdulHakim/Bitcoin-Notifier#10]
Well i will ask here cause i can't ask on https://github.com/MusheAbdulHakim/Smarthr---hr-payroll-project-employee-management-System 

But how can i create an account cause i can't login on it?

**Comment by MusheAbdulHakim** [comment]
username: Vendetta
password : vendetta
or username: Barry password: barry
sorry i didn't add that in the readme.I kinda abondone the project
I might rewrite the project with laravel or codeigniter.
